apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHV5bWdiNWdu
  CLOUDINARY_KEY: OTE1ODg5NjIyMjI1Mzc0
  CLOUDINARY_SECRET: TWhnd1hOZjBWLTdndFJsdV9USkVxR2tOMFM0
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMkZwZG1WdWJtVnNZU0lzSW1FaU9pSmpiVzFwZW1jMWJqSXdNblZzTW5GeU1HUnZOM1F6WkdkakluMC5mRDVCanR4TUVsVUZyVkpDRy15V2JR
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyM0BjbHVzdGVyMC43aHk2dXFrLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
